# Add this to your .readthedocs.yaml file
# Tell Read the Docs which branch to use
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  # This ensures Read the Docs uses the right branch
  clone:
    depth: 50
    shallow: true

# Optional but recommended
vcs:
  type: git
  update:
    checkout: main  # Change 'main' to your actual branch name if different

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
