version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install --upgrade pip
      - pip install -r docs/requirements.txt
    build:
      commands:
        - sphinx-build -b html docs/ docs/_build/html -j auto

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
